### ISSUE TITLE
problem with writefilex

### ISSUE THREAD

**Issue by iamsriki** [palderman/DSSAT#53]
writefilex is giving an error shown below when I'm just trying to execute the command line without any manipulation in the filex.

code that I'm trying to run
jx<-read_filex('./Cotton/GACM0401.COX')
  write_filex(jx,'./Cotton/GACM0401.COX')
Error in `map()`:
i In index: 4.
Caused by error in `all_of()`:
! Can't subset columns that don't exist.
x Columns `PAREA`, `PRNO`, `PLEN`, `PLDR`, `PLSP`, etc. don't exist.
Run `rlang::last_trace()` to see where the error occurred.

The command was running well and good before the installation on new version of R. But after the update we are not able to execute the writefilex which is causing the problem in automisation of the model

**Comment by palderman** [comment]
Hi @iamsriki,

Sorry for the error.

I believe this is the same problem as #51. I plan to release a new package version soon that will address it.

In the mean time, please look there and see if that solution solves it for you.
________________________________
From: iamsriki ***@***.***>
Sent: Monday, January 22, 2024 11:53 PM
To: palderman/DSSAT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [palderman/DSSAT] problem with writefilex (Issue #53)


writefilex is giving an error shown below when I'm just trying to execute the command line without any manipulation in the filex.

code that I'm trying to run
jx<-read_filex('./Cotton/GACM0401.COX')
write_filex(jx,'./Cotton/GACM0401.COX')
Error in map():
i In index: 4.
Caused by error in all_of():
! Can't subset columns that don't exist.
x Columns PAREA, PRNO, PLEN, PLDR, PLSP, etc. don't exist.
Run rlang::last_trace() to see where the error occurred.

The command was running well and good before the installation on new version of R. But after the update we are not able to execute the writefilex which is causing the problem in automisation of the model
